export type RatioTTM = {
  dividendYielTTM: number | null;
  dividendYielPercentageTTM: number | null;
  peRatioTTM: number | null;
  pegRatioTTM: number | null;
  payoutRatioTTM: number | null;
  currentRatioTTM: number | null;
  quickRatioTTM: number | null;
  cashRatioTTM: number | null;
  daysOfSalesOutstandingTTM: number | null;
  daysOfInventoryOutstandingTTM: number | null;
  operatingCycleTTM: number | null;
  daysOfPayablesOutstandingTTM: number | null;
  cashConversionCycleTTM: number | null;
  grossProfitMarginTTM: number | null;
  operatingProfitMarginTTM: number | null;
  pretaxProfitMarginTTM: number | null;
  netProfitMarginTTM: number | null;
  effectiveTaxRateTTM: number | null;
  returnOnAssetsTTM: number | null;
  returnOnEquityTTM: number | null;
  returnOnCapitalEmployedTTM: number | null;
  netIncomePerEBTTTM: number | null;
  ebtPerEbitTTM: number | null;
  ebitPerRevenueTTM: number | null;
  debtRatioTTM: number | null;
  debtEquityRatioTTM: number | null;
  longTermDebtToCapitalizationTTM: number | null;
  totalDebtToCapitalizationTTM: number | null;
  interestCoverageTTM: number | null;
  cashFlowToDebtRatioTTM: number | null;
  companyEquityMultiplierTTM: number | null;
  receivablesTurnoverTTM: number | null;
  payablesTurnoverTTM: number | null;
  inventoryTurnoverTTM: number | null;
  fixedAssetTurnoverTTM: number | null;
  assetTurnoverTTM: number | null;
  operatingCashFlowPerShareTTM: number | null;
  freeCashFlowPerShareTTM: number | null;
  cashPerShareTTM: number | null;
  operatingCashFlowSalesRatioTTM: number | null;
  freeCashFlowOperatingCashFlowRatioTTM: number | null;
  cashFlowCoverageRatiosTTM: number | null;
  shortTermCoverageRatiosTTM: number | null;
  capitalExpenditureCoverageRatioTTM: number | null;
  dividendPaidAndCapexCoverageRatioTTM: number | null;
  priceBookValueRatioTTM: number | null;
  priceToBookRatioTTM: number | null;
  priceToSalesRatioTTM: number | null;
  priceEarningsRatioTTM: number | null;
  priceToFreeCashFlowsRatioTTM: number | null;
  priceToOperatingCashFlowsRatioTTM: number | null;
  priceCashFlowRatioTTM: number | null;
  priceEarningsToGrowthRatioTTM: number | null;
  priceSalesRatioTTM: number | null;
  enterpriseValueMultipleTTM: number | null;
  priceFairValueTTM: number | null;
  dividendPerShareTTM: number | null;
};

export type Ratio = {
  symbol: string;
  date: Date;
  calendarYear: string;
  period: string;
  currentRatio: number | null;
  quickRatio: number | null;
  cashRatio: number | null;
  daysOfSalesOutstanding: number | null;
  daysOfInventoryOutstanding: number | null;
  operatingCycle: number | null;
  daysOfPayablesOutstanding: number | null;
  cashConversionCycle: number | null;
  grossProfitMargin: number | null;
  operatingProfitMargin: number | null;
  pretaxProfitMargin: number | null;
  netProfitMargin: number | null;
  effectiveTaxRate: number | null;
  returnOnAssets: number | null;
  returnOnEquity: number | null;
  returnOnCapitalEmployed: number | null;
  netIncomePerEBT: number | null;
  ebtPerEbit: number | null;
  ebitPerRevenue: number | null;
  debtRatio: number | null;
  debtEquityRatio: number | null;
  longTermDebtToCapitalization: number | null;
  totalDebtToCapitalization: number | null;
  interestCoverage: number | null;
  cashFlowToDebtRatio: number | null;
  companyEquityMultiplier: number | null;
  receivablesTurnover: number | null;
  payablesTurnover: number | null;
  inventoryTurnover: number | null;
  fixedAssetTurnover: number | null;
  assetTurnover: number | null;
  operatingCashFlowPerShare: number | null;
  freeCashFlowPerShare: number | null;
  cashPerShare: number | null;
  payoutRatio: number | null;
  operatingCashFlowSalesRatio: number | null;
  freeCashFlowOperatingCashFlowRatio: number | null;
  cashFlowCoverageRatios: number | null;
  shortTermCoverageRatios: number | null;
  capitalExpenditureCoverageRatio: number | null;
  dividendPaidAndCapexCoverageRatio: number | null;
  dividendPayoutRatio: number | null;
  priceBookValueRatio: number | null;
  priceToBookRatio: number | null;
  priceToSalesRatio: number | null;
  priceEarningsRatio: number | null;
  priceToFreeCashFlowsRatio: number | null;
  priceToOperatingCashFlowsRatio: number | null;
  priceCashFlowRatio: number | null;
  priceEarningsToGrowthRatio: number | null;
  priceSalesRatio: number | null;
  dividendYield: number | null;
  enterpriseValueMultiple: number | null;
  priceFairValue: number | null;
};

export type FinancialPeriod = "annual" | "quarter";

export type Financials = {
  income: IncomeStatement[];
  cash: CashFlowStatement[];
  balance: BalanceSheetStatement[];
};

export type IncomeStatement = {
  date: Date;
  symbol: string;
  reportedCurrency: string;
  cik: string;
  fillingDate: Date;
  acceptedDate: Date;
  calendarYear: string;
  period: string;
  revenue: number | null;
  costOfRevenue: number | null;
  grossProfit: number | null;
  grossProfitRatio: number | null;
  researchAndDevelopmentExpenses: number | null;
  generalAndAdministrativeExpenses: number | null;
  sellingAndMarketingExpenses: number | null;
  sellingGeneralAndAdministrativeExpenses: number | null;
  otherExpenses: number | null;
  operatingExpenses: number | null;
  costAndExpenses: number | null;
  interestIncome: number | null;
  interestExpense: number | null;
  depreciationAndAmortization: number | null;
  ebitda: number | null;
  ebitdaratio: number | null;
  operatingIncome: number | null;
  operatingIncomeRatio: number | null;
  totalOtherIncomeExpensesNet: number | null;
  incomeBeforeTax: number | null;
  incomeBeforeTaxRatio: number | null;
  incomeTaxExpense: number | null;
  netIncome: number | null;
  netIncomeRatio: number | null;
  eps: number | null;
  epsdiluted: number | null;
  weightedAverageShsOut: number | null;
  weightedAverageShsOutDil: number | null;
  link: string | null;
  finalLink: string | null;
};

export type CashFlowStatement = {
  date: Date;
  symbol: string;
  reportedCurrency: string;
  cik: string;
  fillingDate: Date;
  acceptedDate: Date;
  calendarYear: string;
  period: string;
  netIncome: number | null;
  depreciationAndAmortization: number | null;
  deferredIncomeTax: number | null;
  stockBasedCompensation: number | null;
  changeInWorkingCapital: number | null;
  accountsReceivables: number | null;
  inventory: number | null;
  accountsPayables: number | null;
  otherWorkingCapital: number | null;
  otherNonCashItems: number | null;
  netCashProvidedByOperatingActivities: number | null;
  investmentsInPropertyPlantAndEquipment: number | null;
  acquisitionsNet: number | null;
  purchasesOfInvestments: number | null;
  salesMaturitiesOfInvestments: number | null;
  otherInvestingActivites: number | null;
  netCashUsedForInvestingActivites: number | null;
  debtRepayment: number | null;
  commonStockIssued: number | null;
  commonStockRepurchased: number | null;
  dividendsPaid: number | null;
  otherFinancingActivites: number | null;
  netCashUsedProvidedByFinancingActivities: number | null;
  effectOfForexChangesOnCash: number | null;
  netChangeInCash: number | null;
  cashAtEndOfPeriod: number | null;
  cashAtBeginningOfPeriod: number | null;
  operatingCashFlow: number | null;
  capitalExpenditure: number | null;
  freeCashFlow: number | null;
  link: string | null;
  finalLink: string | null;
};

export type BalanceSheetStatement = {
  date: Date;
  symbol: string;
  reportedCurrency: string;
  cik: string;
  fillingDate: Date;
  acceptedDate: Date;
  calendarYear: string;
  period: string;
  cashAndCashEquivalents: number | null;
  shortTermInvestments: number | null;
  cashAndShortTermInvestments: number | null;
  netReceivables: number | null;
  inventory: number | null;
  otherCurrentAssets: number | null;
  totalCurrentAssets: number | null;
  propertyPlantEquipmentNet: number | null;
  goodwill: number | null;
  intangibleAssets: number | null;
  goodwillAndIntangibleAssets: number | null;
  longTermInvestments: number | null;
  taxAssets: number | null;
  otherNonCurrentAssets: number | null;
  totalNonCurrentAssets: number | null;
  otherAssets: number | null;
  totalAssets: number | null;
  accountPayables: number | null;
  shortTermDebt: number | null;
  taxPayables: number | null;
  deferredRevenue: number | null;
  otherCurrentLiabilities: number | null;
  totalCurrentLiabilities: number | null;
  longTermDebt: number | null;
  deferredRevenueNonCurrent: number | null;
  deferredTaxLiabilitiesNonCurrent: number | null;
  otherNonCurrentLiabilities: number | null;
  totalNonCurrentLiabilities: number | null;
  otherLiabilities: number | null;
  capitalLeaseObligations: number | null;
  totalLiabilities: number | null;
  preferredStock: number | null;
  commonStock: number | null;
  retainedEarnings: number | null;
  accumulatedOtherComprehensiveIncomeLoss: number | null;
  othertotalStockholdersEquity: number | null;
  totalStockholdersEquity: number | null;
  totalEquity: number | null;
  totalLiabilitiesAndStockholdersEquity: number | null;
  minorityInterest: number | null;
  totalLiabilitiesAndTotalEquity: number | null;
  totalInvestments: number | null;
  totalDebt: number | null;
  netDebt: number | null;
  link: string | null;
  finalLink: string | null;
};

export type SecFiling = {
  symbol: string;
  fillingDate: Date;
  acceptedDate: Date;
  cik: string;
  type: string;
  link: string;
  finalLink: string;
};

export type FinancialGrowth = {
  symbol: string;
  date: Date;
  calendarYear: string;
  period: string;
  revenueGrowth: number | null;
  grossProfitGrowth: number | null;
  ebitgrowth: number | null;
  operatingIncomeGrowth: number | null;
  netIncomeGrowth: number | null;
  epsgrowth: number | null;
  epsdilutedGrowth: number | null;
  weightedAverageSharesGrowth: number | null;
  weightedAverageSharesDilutedGrowth: number | null;
  dividendsperShareGrowth: number | null;
  operatingCashFlowGrowth: number | null;
  freeCashFlowGrowth: number | null;
  tenYRevenueGrowthPerShare: number | null;
  fiveYRevenueGrowthPerShare: number | null;
  threeYRevenueGrowthPerShare: number | null;
  tenYOperatingCFGrowthPerShare: number | null;
  fiveYOperatingCFGrowthPerShare: number | null;
  threeYOperatingCFGrowthPerShare: number | null;
  tenYNetIncomeGrowthPerShare: number | null;
  fiveYNetIncomeGrowthPerShare: number | null;
  threeYNetIncomeGrowthPerShare: number | null;
  tenYShareholdersEquityGrowthPerShare: number | null;
  fiveYShareholdersEquityGrowthPerShare: number | null;
  threeYShareholdersEquityGrowthPerShare: number | null;
  tenYDividendperShareGrowthPerShare: number | null;
  fiveYDividendperShareGrowthPerShare: number | null;
  threeYDividendperShareGrowthPerShare: number | null;
  receivablesGrowth: number | null;
  inventoryGrowth: number | null;
  assetGrowth: number | null;
  bookValueperShareGrowth: number | null;
  debtGrowth: number | null;
  rdexpenseGrowth: number | null;
  sgaexpensesGrowth: number | null;
};

export type BalanceSheetStatementGrowth = {
  date: Date;
  symbol: string;
  calendarYear: string;
  period: string;
  growthCashAndCashEquivalents: number | null;
  growthShortTermInvestments: number | null;
  growthCashAndShortTermInvestments: number | null;
  growthNetReceivables: number | null;
  growthInventory: number | null;
  growthOtherCurrentAssets: number | null;
  growthTotalCurrentAssets: number | null;
  growthPropertyPlantEquipmentNet: number | null;
  growthGoodwill: number | null;
  growthIntangibleAssets: number | null;
  growthGoodwillAndIntangibleAssets: number | null;
  growthLongTermInvestments: number | null;
  growthTaxAssets: number | null;
  growthOtherNonCurrentAssets: number | null;
  growthTotalNonCurrentAssets: number | null;
  growthOtherAssets: number | null;
  growthTotalAssets: number | null;
  growthAccountPayables: number | null;
  growthShortTermDebt: number | null;
  growthTaxPayables: number | null;
  growthDeferredRevenue: number | null;
  growthOtherCurrentLiabilities: number | null;
  growthTotalCurrentLiabilities: number | null;
  growthLongTermDebt: number | null;
  growthDeferredRevenueNonCurrent: number | null;
  growthDeferrredTaxLiabilitiesNonCurrent: number | null;
  growthOtherNonCurrentLiabilities: number | null;
  growthTotalNonCurrentLiabilities: number | null;
  growthOtherLiabilities: number | null;
  growthTotalLiabilities: number | null;
  growthCommonStock: number | null;
  growthRetainedEarnings: number | null;
  growthAccumulatedOtherComprehensiveIncomeLoss: number | null;
  growthOthertotalStockholdersEquity: number | null;
  growthTotalStockholdersEquity: number | null;
  growthTotalLiabilitiesAndStockholdersEquity: number | null;
  growthTotalInvestments: number | null;
  growthTotalDebt: number | null;
  growthNetDebt: number | null;
};

export type IncomeStatementGrowth = {
  date: Date;
  symbol: string;
  calendarYear: string;
  period: string;
  growthRevenue: number | null;
  growthCostOfRevenue: number | null;
  growthGrossProfit: number | null;
  growthGrossProfitRatio: number | null;
  growthResearchAndDevelopmentExpenses: number | null;
  growthGeneralAndAdministrativeExpenses: number | null;
  growthSellingAndMarketingExpenses: number | null;
  growthOtherExpenses: number | null;
  growthOperatingExpenses: number | null;
  growthCostAndExpenses: number | null;
  growthInterestExpense: number | null;
  growthDepreciationAndAmortization: number | null;
  growthEBITDA: number | null;
  growthEBITDARatio: number | null;
  growthOperatingIncome: number | null;
  growthOperatingIncomeRatio: number | null;
  growthTotalOtherIncomeExpensesNet: number | null;
  growthIncomeBeforeTax: number | null;
  growthIncomeBeforeTaxRatio: number | null;
  growthIncomeTaxExpense: number | null;
  growthNetIncome: number | null;
  growthNetIncomeRatio: number | null;
  growthEPS: number | null;
  growthEPSDiluted: number | null;
  growthWeightedAverageShsOut: number | null;
  growthWeightedAverageShsOutDil: number | null;
};

export type CashFlowStatementGrowth = {
  date: Date;
  symbol: string;
  calendarYear: string;
  period: string;
  growthNetIncome: number | null;
  growthDepreciationAndAmortization: number | null;
  growthDeferredIncomeTax: number | null;
  growthStockBasedCompensation: number | null;
  growthChangeInWorkingCapital: number | null;
  growthAccountsReceivables: number | null;
  growthInventory: number | null;
  growthAccountsPayables: number | null;
  growthOtherWorkingCapital: number | null;
  growthOtherNonCashItems: number | null;
  growthNetCashProvidedByOperatingActivites: number | null;
  growthInvestmentsInPropertyPlantAndEquipment: number | null;
  growthAcquisitionsNet: number | null;
  growthPurchasesOfInvestments: number | null;
  growthSalesMaturitiesOfInvestments: number | null;
  growthOtherInvestingActivites: number | null;
  growthNetCashUsedForInvestingActivites: number | null;
  growthDebtRepayment: number | null;
  growthCommonStockIssued: number | null;
  growthCommonStockRepurchased: number | null;
  growthDividendsPaid: number | null;
  growthOtherFinancingActivites: number | null;
  growthNetCashUsedProvidedByFinancingActivities: number | null;
  growthEffectOfForexChangesOnCash: number | null;
  growthNetChangeInCash: number | null;
  growthCashAtEndOfPeriod: number | null;
  growthCashAtBeginningOfPeriod: number | null;
  growthOperatingCashFlow: number | null;
  growthCapitalExpenditure: number | null;
  growthFreeCashFlow: number | null;
};
