import { ZodType, z } from "zod";
import { CompanyKeyExecutive, CompanyProfile } from "../types";

export const CompanyProfileSchema = z.object({
  symbol: z.string(),
  price: z.number(),
  beta: z.number(),
  volAvg: z.number(),
  mktCap: z.number(),
  lastDiv: z.number(),
  range: z.string(),
  changes: z.number(),
  companyName: z.string(),
  currency: z.string(),
  cik: z.string(),
  isin: z.string(),
  cusip: z.string(),
  exchange: z.string(),
  exchangeShortName: z.string(),
  industry: z.string(),
  website: z.string(),
  description: z.string(),
  ceo: z.string(),
  sector: z.string(),
  country: z.string(),
  fullTimeEmployees: z.string(),
  phone: z.string(),
  address: z.string(),
  city: z.string(),
  state: z.string(),
  zip: z.string(),
  dcfDiff: z.number(),
  dcf: z.number(),
  image: z.string(),
  ipoDate: z.coerce.date(),
  defaultImage: z.boolean(),
  isEtf: z.boolean(),
  isActivelyTrading: z.boolean(),
  isAdr: z.boolean(),
  isFund: z.boolean(),
}) satisfies ZodType<CompanyProfile>;

export const CompanyKeyExecutiveSchema = z.object({
  title: z.string(),
  name: z.string(),
  pay: z.union([z.number(), z.null()]),
  currencyPay: z.string(),
  gender: z.string(),
  yearBorn: z.union([z.number(), z.null()]),
  titleSince: z.union([z.null(), z.coerce.date()]),
}) satisfies ZodType<CompanyKeyExecutive>;
